default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: womenrising_development

test:
  <<: *default
  database: womenrising_test

production:
  <<: *default
  database: womenrising_production
  username: womenrising
  password: <%= ENV['WOMENRISING_DATABASE_PASSWORD'] %>
